# Generated by Django 5.0.3 on 2024-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeSnippetSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                (
                    "code_language",
                    models.CharField(
                        choices=[
                            ("C++", "c++"),
                            ("Python", "python"),
                            ("Java", "java"),
                            ("Javascript", "javascript"),
                        ],
                        max_length=10,
                    ),
                ),
                ("code_snippet", models.TextField()),
                ("stdinput", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stdoutput", models.TextField()),
            ],
        ),
    ]
